### ISSUE TITLE
Warn or Prevent Deploying with the git tagging adapter if the branch is dirty

### ISSUE THREAD

**Issue by danshultz** [ember-cli-deploy/ember-cli-deploy#102]
The index is tagged based on the current git hash when using the default tagging adapter. When one completes an `ember deploy` with a dirty branch, the deploy is not accurate based on the git hash and can possibly prevent a valid deploy.

It would be helpful to warn or prevent deploying from a dirty git brach. We also could prevent running `ember deploy` from a dirty branch. If one wants to run `ember deploy` from a dirty git branch when using the default sha tagging adapter, we could require a `--force` or `-f` flag to explicitly opt in.

**Comment by achambers** [comment]
:+1:

**Comment by jabbermarky** [comment]
:thumbsup:

**Comment by lukemelia** [comment]
@achambers feels like this could be a config option on revision-data plugin. Or, could be a tiny standalong plugin. WDYT?

**Comment by Bockit** [comment]
This sounds like the kind of thing the `willDeploy` hook was designed for. I need this at the moment and have the following quick-hack in-repo addon working. The `--force` stuff is interesting, is there something in place already for passing cli arguments to addons or do we parse it ourselves?

```javascript
var BasePlugin = require('ember-cli-deploy-plugin');
var gitState = require('git-state')

module.exports = {
  name: 'ember-cli-deploy-check-repo-clean',

  createDeployPlugin: function (options) {
    var DeployPlugin = BasePlugin.extend({
      name: options.name,

      willDeploy: function (context) {
        var _this = this;

        return new Promise(function (resolve, reject) {
          var gitDir = context.project.root;
          
          gitState.dirty(gitDir, function (err, dirtyCount) {
            if (err) {
              _this.log(err.stack, { color: 'red' });
              reject(err);
            }

            if (dirtyCount) {
              _this.log('The git working directory has dirty files. Please commit or stash your changes.', { color: 'yellow' });
              reject(new Error('Dirty working directory'));
            }

            resolve();
          });
        })
      }
    });

    return new DeployPlugin();
  }
};
```

**Comment by ghedamat** [comment]
@Bockit I guess that your example proves this could be a separate plugin (which to me seems the most general solution).

let us know if you ended up releasing something like the above!

@lukemelia I'd say we can close this but we should not loose track and possibly add mention of this in the docs/cookbooks

**Comment by duizendnegen** [comment]
@Bockit - if this plug-in is something you published or want to publish, please let me know so we can add it to the list of known plug-ins.
Closing this for now, as `ember-cli-deploy` supports this workflow as demonstrated above.
