### ISSUE TITLE
There should be an alternative way to specify a plugins name

### ISSUE THREAD

**Issue by jasonkriss** [ember-cli-deploy/ember-cli-deploy#198]
[As of now](https://github.com/ember-cli/ember-cli-deploy/blob/v0.5.0-beta.1/lib/tasks/pipeline.js#L145), ember-cli-deploy is implicitly requiring that plugins have names like `ember-cli-deploy-[plugin]`. While this definitely seems like a good convention to have, I think we should allow an escape valve for people who want/need to name their addon differently.

**Comment by achambers** [comment]
@jasonkriss I've been silently following this discussion on slack. What is an example of where you'd want to name it differently?

**Comment by lukemelia** [comment]
An idea of how to accomplish this would be to allow a developer to specify a name via their package.json:

```
  ...
  "ember-addon": {
    "ember-cli-deploy-plugin-name": "fooey"
  }
  ...
```

By relying on the package name, we get a natural suggestion of uniqueness since package names have to be unique on npm. Our configuration model cannot accommodate two plugins with the same name. In practice, I don't think this will be an issue, but just wanted to mention it as a consideration.

**Comment by jasonkriss** [comment]
@achambers Let me just preface this by saying that I'm not completely opposed to keeping it the way it is now. I think you guys have considered the reasoning behind this more than I have. That being said, my use case is basically that i want to have an addon that is both a ember-cli-deploy-plugin as well as ember-cli-deploy-plugin-pack. The reason I want to do this is that I’m building a deploy process that doesn’t make sense independently at all and is completely dependent on both the `build` and `gzip` plugins. Being forced to name it something like `ember-cli-deploy-[plugin]` just isn't as meaningful in this case.

This whole argument is moot if an addon can't be both a plugin and a pack though. @lukemelia I definitely see your point on the uniqueness aspect. Realistically, this might be reason enough to enforce the naming constraint.

At the very least, I think we'll need to make sure the documentation makes it clear that the name format is a strict requirement.

**Comment by duizendnegen** [comment]
In `1.0.x` we started supporting aliasing - please try the `beta-1` package and let us know if there's anything additionally that this change doesn't cover.

I'm closing this issue now, but I'd be happy to learn more about your deploy process & see how it can fit to `ember-cli-deploy`.
