### ISSUE TITLE
Layout breakage on some Docs pages with Center-panel

### ISSUE THREAD

**Issue by sheriffderek** [ember-cli-deploy/ember-cli-deploy#370]
There is some layout breakage on some Docs pages with Center-panel.
<img width="740" alt="screen shot 2016-02-28 at 9 32 48 am" src="https://cloud.githubusercontent.com/assets/2066617/13380883/3fd9c37e-de02-11e5-8d8d-e6e805e2a6aa.png">

Pages I've seen it on:
http://ember-cli.com/ember-cli-deploy/docs/v0.6.x/plugins
http://ember-cli.com/ember-cli-deploy/docs/v0.6.x/writing-a-plugin

They are set to 68% with flex, just like the other pages, but something is not obeying.
It's only at the 768px break-point.

Just noting that while I remembered. : )

**Comment by ghedamat** [comment]
@sheriffderek sorry for the delay and thanks for pointing this out!

Are you interested in attempting a fix? it's probably due to one of the mandatory updates to gh-pages and the markdown renderer

**Comment by sheriffderek** [comment]
I'll try and sort it out if someone doesn't get to it first.

**Comment by ghedamat** [comment]
thanks! appreciated :)

**Comment by ghedamat** [comment]
shoud be fixed by #413 (at least in the 1.0.X branch)

**Comment by duizendnegen** [comment]
Closing as allegedly fixed in 1.x
