### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by backspace** [ember-cli-deploy/ember-cli-deploy#387]
At least it is for me!

![image](https://cloud.githubusercontent.com/assets/43280/14520755/8e44da42-0226-11e6-8a42-bf0ba4abc8b6.png)

I don’t see any [GitHub status problems](https://status.github.com/).

I’m not sure how the site is set up as a directory on ember-cli.com, so maybe the problem is with that.

**Comment by achambers** [comment]
Have updated the DNS forwarding which might take a couple of hours to update. Will keep an eye on it

**Comment by lukemelia** [comment]
Thanks @achambers. Looks good for me in NYC now.

**Comment by achambers** [comment]
👍 Yep, looks fine in London...Going to close this now.
