### ISSUE TITLE
Clarify s3 prefix setup that comes with lightning pack?

### ISSUE THREAD

**Issue by acorncom** [ember-cli-deploy/ember-cli-deploy#396]
Happy to send in a PR on this, but wanted to open this issue to make sure I knew what to do in the PR 😄 

Background: I'm upgrading from `ember-cli-deploy#0.4.0` and had an existing setup working there (which included use of the Fingerprinting instructions: http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/fingerprinting/)

I setup using the `ember-cli-deploy-lightning-pack` plugin pack (and in essence threw away our old config) as we hadn't made major changes.  But in the changeover, our index.html file started referencing nonexistent S3 files. Looks like my problem was related to this line in the lightning-pack setup: https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/blob/master/blueprints/lightning-deploy-config/files/config/deploy.js#L15

Specifically, everything was being deployed to `app-name/` on S3 (with the new config) but my old code, the Fingerprinting page and the file asset upload example (http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/s3-walkthrough/#uploading-to-s3) don't mention the `app-name/` folder aspect and instead assume `/assets`.  Seems like that's due to the blueprint setting for `lightning-pack` and not an S3 default option.

My fix was to change what my fingerprint `prepend` was set to from `https://cloudfront-id.cloudfront.net/` -> `https://cloudfront-id.cloudfront.net/app-name` and then everything worked.

Should we adjust the docs in any way on this or just chalk it up to upgrade headaches on my end? 😀   Now that I know what I'm looking for, I'm seeing the proper mention of `app-name/assets` when deploying using verbose mode.  But it took a while to catch all of this ;-)

Thanks for all your work, I'm enjoying `v0.6.0` a bunch! 👍

**Comment by lukemelia** [comment]
I'm glad you got it figured out @acorncom. Certainly seems like some additional docs could help. It seems like perhaps the best place for this would the README of ember-cli-deploy-lightning-pack.

**Comment by acorncom** [comment]
Sounds good, closing this here
