### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by ksnyde** [ember-cli-deploy/ember-cli-deploy#397]
I'm new to ember-cli and getting an error -- `Cannot convert object to primitive value` -- which I don't know what to do with. 

Here's what I've installed as dependencies in `package.json`:

    "ember-cli-deploy": "0.6.1",
    "ember-cli-deploy-s3": "0.3.0",
    "ember-cli-deploy-slack": "^0.1.0",

In my `deploy.js`:

    plugins: [
      "ember-cli-deploy-s3:s3-fingerprinted",
      "ember-cli-deploy-s3:s3-index",
      "ember-cli-deploy-s3:s3-finger-free",
    ],
    ['s3-fingerprinted']: {
      accessKeyId: 'accesskey',
      secretAccessKey: 'secret',
      region: 'eu-west'
      bucket: 'my-bucket',
    },
    ['s3-index']: {
      accessKeyId: 'accesskey',
      secretAccessKey: 'secret',
      region: 'eu-west',
      bucket: 'my-bucket',
      manifestPath: null,
      filePattern: '**/index.js',
      cacheControl: 'max-age: 15',
      expires: 15
    },
    ['s3-finger-free']: {
      accessKeyId: 'accesskey',
      secretAccessKey: 'secret',
      region: 'eu-west',
      bucket: 'my-bucket',
      manifestPath: null,
      filePattern: '**/(robots.txt|crossdomain.xml)',
      cacheControl: 'max-age: 3600',
      expires: 3600
    },

Then I run the `ember deploy staging` and get:

```sh
TypeError: Cannot convert object to primitive value
    at String (native)
    at Function.applyStyle (/path/to/project/node_modules/chalk/index.js:57:29)
    at Chalk.builder (/path/to/project/node_modules/chalk/index.js:40:21)
    at writeError (/path/to/project/node_modules/ember-cli/lib/ui/write-error.js:19:24)
    at UI.writeError (/path/to/projectnode_modules/ember-cli/lib/ui/index.js:158:3)
    at Class.module.exports.Task.extend._configuredPlugins (/path/to/project/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:115:15)
    at Class.module.exports.Task.extend.setup (/path/to/project/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:37:22)
    at Class.module.exports.Task.extend.run (/path/to/project/node_modules/ember-cli-deploy/lib/tasks/pipeline.js:87:10)
    at Class.module.exports.Task.extend.run (/path/to/project/node_modules/ember-cli-deploy/lib/tasks/deploy.js:19:21)
    at /path/to/project/node_modules/ember-cli-deploy/lib/commands/deploy.js:53:21
```

**Comment by achambers** [comment]
@ksnyde Do you have the build plugin installed?

**Comment by ksnyde** [comment]
@achambers what good would a _build_ plugin be? 😉 

In all seriousness, I don't have it. Shouldn't that be in the "installation" section of the docs? Now that I'm looking for it I do see it in the quick start section but you know us developer types ... always skipping documentation, etc. Think they know it all, don't they. Well maybe it's just me. I hope not but thanks for getting back on the straight and narrow.

**Comment by ksnyde** [comment]
Hmmm. I now have `build` in there:

    "ember-cli-deploy": "0.6.1",
    "ember-cli-deploy-build": "0.1.1",
    "ember-cli-deploy-s3": "0.3.0",
    "ember-cli-deploy-slack": "^0.1.0",

but still get the same error 😢

**Comment by ghedamat** [comment]
hey @ksnyde did you also add the build plugin to the `plugins` list in your config?

if you specify a custom `plugins` option you then have to list all the plugins (see http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/configuration-overview/)

you could also try to run your deploy command with the `--verbose` option to see more debugging information.

lastly I think this might be easier to diagnose on the ember community slack in the #ec-deploy channel, maybe ping us there tomorrow?

once we have more info we can clarify or close this issue

**Comment by LevelbossMike** [comment]
This is actually related to https://github.com/ember-cli-deploy/ember-cli-deploy-slack/issues/13

https://github.com/ember-cli-deploy/ember-cli-deploy/blob/master/lib/tasks/pipeline.js#L115 is the problem and this can be solved by `JSON.stringify`-ing the error there. Because we are stubbing the ui in the tests this didn't create problems in our tests.

I'll create a pr for this in the next days. Not sure if I have the time today for this.

**Comment by ksnyde** [comment]
@ghedamat Oh great, hadn't realised there was a channel on slack and to your earlier question ... unfortunately the `--verbose` flag doesn't give any additional info in this case.

**Comment by ksnyde** [comment]
@LevelbossMike great pointer, if that's all that's needed maybe I'll just drop the PR in today. I'd love to see this work today (even if I'm supposed to be focused on talk I'm giving tomorrow).

**Comment by ksnyde** [comment]
@LevelbossMike I've put in the PR, will add a unit test tomorrow. Tested it locally and it works as you'd expect but interestingly what I get back now is:

```js
{
  "ember-cli-deploy-build": "ember-cli-deploy-build",
  "s3-fingerprinted": "ember-cli-deploy-s3",
  "s3-index": "ember-cli-deploy-s3",
  "s3-finger-free": "ember-cli-deploy-s3"
}
plugins configuration references plugins which are not available.
```

Does this really mean that NONE of my installed plugins are installed (note: I removed slack step for the time being)?

**Comment by LevelbossMike** [comment]
Cool and thx you took the time to create that pr!

I tried that out and it only listed the plugins I hadn't configured. Are you using the s3 plugin as well in your test project? because the index plugin is called "ember-cli-deploy-s3-index" and you are aliasing "ember-cli-deploy-s3".

Also you are returning an ENV-object from the function that you implement from deploy.js and the syntax for that looks strange in your example.

```javascript
module.exports = function(deployTarget) {

  var ENV = {
    "s3-fingerprinted": {
      // options go here
    } 
   // ...
  }
}
```

would look more like the way you are supposed to configure plugins via deploy.js. So yes maybe none of the plugins are installed but I don't have access to your test project to verify.

**Comment by ksnyde** [comment]
I'm using "ember-cli-deploy-s3" only right now with multiple aliases (one of which is intended to cover the `index.html` use-case). Once I get that working I will look to see if the s3-index plugin can offer me some additional benefit.

**Comment by ksnyde** [comment]
Ok, thanks to help from @achambers I'm closing this. I was incorrectly using a fully qualified name for the plugins (aka, `ember-cli-deploy-s3` instead of just `s3`). Doh.
