### ISSUE TITLE
ember-cli-deploy

### ISSUE THREAD

**Issue by samselikoff** [ember-cli-deploy/ember-cli-deploy#4]
Just wanted to ping about [ember-cli-deploy](https://github.com/achambers/ember-cli-deploy) to make sure we're sharing as much work as possible. Are there some fundamental differences to your approach?

**Comment by acorncom** [comment]
@achambers @LevelbossMike Any updates on the direction this is going to go?  We're planning on using this approach to deploying and I'd love to know if there is a particular bandwagon I should be jumping on ;-)  Thanks!

**Comment by achambers** [comment]
Hi @acorncom. Yep, there will be some updates shortly. We've got a few things to sort out first. Glad you're interested in the approach. More details to come shortly.

**Comment by acorncom** [comment]
@achambers Appreciate it.  We had been thinking of putting that in in the next week or so, would you recommend we hold off for now?

**Comment by achambers** [comment]
@acorncom Depends on how soon you want to get it in. If you want to move forward now, I'd suggest using this repo (Mike's ember-deploy) for the time being. This should put you in good stead for the path forward.

**Comment by acorncom** [comment]
@achambers That's quite helpful.  And yes, we were thinking of starting work on it in the next few days.  Looking forward to what you guys cook up!

**Comment by varblob** [comment]
@achambers  I second the helpfulness of your comment.   

You currently own top search position for a number of different versions of trying to deploy ember do you think you could put a note in your readme to point new people towards this version / mention the future collaboration.

**Comment by achambers** [comment]
Yep. Will be doing this shortly. We were only discussing yesterday about the way forward.
