### ISSUE TITLE
Testing example in docs throws Error: Cannot find module 'ember-cli/tests/helpers/assert'

### ISSUE THREAD

**Issue by chrisdpeters** [ember-cli-deploy/ember-cli-deploy#408]
The [0.6.x docs](http://ember-cli-deploy.github.io/ember-cli-deploy/docs/v0.6.x/writing-a-plugin/) suggest requiring `asset` as such in `tests/unit/index-nodetest.js`:

``` javascript
var assert  = require('ember-cli/tests/helpers/assert');
```

But now that throws an error:

```
Error: Cannot find module 'ember-cli/tests/helpers/assert'
```

As @lukemelia [pointed out in the #ec-deploy Slack channel](https://embercommunity.slack.com/archives/ec-deploy/p1465567284000035), that file has been removed from Ember CLI and moved into a separate [ember-cli-internal-test-helpers](https://github.com/ember-cli/ember-cli-internal-test-helpers) project.

It sounds like an option would be for the docs to suggest including ember-cli-internal-test-helpers, but the word "internal" in the project gives Luke pause. But if you review the contents of [lib/helpers/assert.js](https://github.com/ember-cli/ember-cli-internal-test-helpers/blob/master/lib/helpers/assert.js) of that project, you'll notice that its main job is to reference chai's `assert`.

So then the other option is for the docs to suggest including chai instead.

I'm happy either way as long as it works. 😄  Let me know if there is anything I can do to help, including a PR for new docs.

**Comment by chrisdpeters** [comment]
For those who are Googling this error, here is my workaround until this issue is resolved:

``bash
npm install chai --save-dev
npm install chai-as-promised --save-dev
``

Then create a file at `tests/helpers/assert.js`:

```javascript
var chai           = require('chai');
var chaiAsPromised = require('chai-as-promised');

chai.use(chaiAsPromised);

module.exports = chai.assert;
```

Then change the `require` call in `tests/unit/index-nodetest.js`:

```javascript
var assert  = require('../helpers/assert');
```

**Comment by ghedamat** [comment]
@chrisdpeters would you be interested in opening a pr against our docs with your suggested change?

should be both for 0.6 and 1.0 docs (the content is the same)

let me know and thanks a lot!

/cc @lukemelia

**Comment by chrisdpeters** [comment]
@ghedamat I'd be happy to!

Would you prefer that I document the steps for the workaround or for instead including from `ember-cli-internal-test-helpers`?

**Comment by ghedamat** [comment]
I think the workaround. We should have chai as a dependency anyway unless I'm mistaken.
Or we can suggest to add it if needed.

**Comment by chrisdpeters** [comment]
@ghedamat Yes, [they are dev dependencies already](https://github.com/ember-cli-deploy/ember-cli-deploy/blob/027bf9ff2462ceed00e733d6481d983d4f95018d/package.json#L23-L24).

I'll submit a pull request in the next few days.

**Comment by duizendnegen** [comment]
Updating docs, closing this.
