### ISSUE TITLE
Link to upgrade notes in the v1.0.0-beta.1 release is broken

### ISSUE THREAD

**Issue by acorncom** [ember-cli-deploy/ember-cli-deploy#420]
At the bottom of the release notes for the v1.0.0-beta.1 release, there is a link to the upgrade notes:
![screen shot 2016-07-12 at 10 13 20 am](https://cloud.githubusercontent.com/assets/802505/16774470/4d844ff4-4819-11e6-910d-1e117dd6269a.png)

It currently points to http://ember-cli-deploy.com/docs/v1.0.x-beta.1/upgrading/ but you get a 404 when following the link.  The actual link should be http://ember-cli-deploy.com/docs/v1.0.0-beta.1/upgrading/

Thanks for all your hard work on this!

**Comment by ghedamat** [comment]
fixed @acorncom 

thanks!
