### ISSUE TITLE
Build step of deploy is much slower than typical build

### ISSUE THREAD

**Issue by dzaman** [ember-cli-deploy/ember-cli-deploy#422]
When I run `ember s` it takes about 1-2 seconds, but when I run `ember deploy <env>` it takes almost a minute, and almost all of that time is spent in the `building app to 'tmp/deploy-dist' using buildEnv <buildEnv>` phase.

Is this typical/expected? If not, do you have any recommendations for how to track down what parts are the slowest?

I have the following related packages active:
* ember-cli-deploy-build
* ember-cli-deploy-display-revisions
* ember-cli-deploy-gzip
* ember-cli-deploy-manifest
* ember-cli-deploy-revision-data
* ember-cli-deploy-s3
* ember-cli-deploy-s3-index

**Comment by lukemelia** [comment]
@dzaman the equivalent command to compare to is `ember build --environment=production`

I suspect that minification is the slowest piece.

**Comment by dzaman** [comment]
@lukemelia, thanks for pointing me in the right direction!

**Comment by achambers** [comment]
Closing due to this not being an issue with ember-cli-deploy. Any other probs, ping us in the #ec-deploy channel on the ember community slack team or reopen the issue.
