### ISSUE TITLE
Upgrading ember-deploy-couchbase for ember-cli-deploy >= 0.5.0

### ISSUE THREAD

**Issue by archit** [ember-cli-deploy/ember-cli-deploy#425]
Hey all, I'm the maintainer of [ember-deploy-couchbase](https://github.com/waltznetworks/ember-deploy-couchbase). I'm in the process of upgrading it to ember-cli-deploy >= 0.5.0 and figured I'd ask for help, as is mentioned here in your [docs here](http://ember-cli-deploy.com/docs/v0.6.x/plugins/).

Is the upgrade ember-cli-deploy 0.5.0 and 0.6.0 compatible? Or were there more breaking changes in the plugin API between those 2 versions? Please advise, where should I look to read about upgrading the plugin.

**Comment by ghedamat** [comment]
hi @archit 

we're currently on 1.0.0-beta.1 and all the upgrades from 0.5 upwards do not have breaking changes so you should be good


you should have all the base info here

http://ember-cli-deploy.com/docs/v0.6.x/upgrading-plugins/

but if you get stuck ping us on the #ec-deploy channel of the ember community slack!

thanks for doing this!

**Comment by archit** [comment]
@ghedamat Hey so I got an alpha version of the upgraded plugin published 

on npmjs.org: https://www.npmjs.com/package/ember-cli-deploy-couchbase
on GitHub: https://github.com/waltznetworks/ember-cli-deploy-couchbase

I took the approach of `ember-deploy-s3`/`ember-cli-deploy-s3` and took this opportunity to rename the plugin `ember-cli-deploy-couchbase` (thanks to @DanielCMS).

I've tested it with ember-cli-deploy `0.6.4` and `1.0.0-beta.1`, and its reached feature parity with `ember-deploy-couchbase`.

**Comment by archit** [comment]
ping.

**Comment by duizendnegen** [comment]
Hi @archit - what information are you waiting for? If you want your plug-in to be included in the docs, feel free to open a PR adding it to the list.

**Comment by archit** [comment]
duizendnegen, ah yes. makes sense. I think I had created this issue, cuz I needed a heads up on any upgrade issues. Those have obviously been resolved. So I'll close this Issue.
