### ISSUE TITLE
default config doesn't return ENV

### ISSUE THREAD

**Issue by afgallo** [ember-cli-deploy/ember-cli-deploy#428]
After having installed ember-cli-deploy and followed the steps for a basic deployment workflow, I get the following error:

> Cannot read property 'pipeline' of undefined
> TypeError: Cannot read property 'pipeline' of undefined
>     at CoreObject.module.exports.Task.extend._shouldActivate (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/ember-cli-deploy/lib/tasks/deploy.js:27:37)
>     at CoreObject.module.exports.Task.extend.init (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/ember-cli-deploy/lib/tasks/deploy.js:11:55)
>     at CoreObject.superWrapper [as init] (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/core-object/lib/assign-properties.js:32:18)
>     at CoreObject.Class (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/core-object/core-object.js:32:33)
>     at /Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/ember-cli-deploy/lib/commands/deploy.js:45:20
>     at tryCatch (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/rsvp/dist/rsvp.js:538:12)
>     at invokeCallback (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/rsvp/dist/rsvp.js:553:13)
>     at /Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/rsvp/dist/rsvp.js:628:16
>     at flush (/Users/afgallo/Code/aangaba/dashboard.angaaba.com/node_modules/rsvp/dist/rsvp.js:2370:5)
>     at _combinedTickCallback (internal/process/next_tick.js:67:7)

What am I missing?

ember-cli-deploy installed packages:

    "ember-cli-deploy": "1.0.0-beta.1",
    "ember-cli-deploy-azure": "0.2.7",
    "ember-cli-deploy-build": "0.1.1"

**Comment by achambers** [comment]
Hi @afgallo . Could you please provide some more context? Please provide gists of the following:

- [ ] package.json
- [ ] config/deploy.js
- [ ] output of `ember deploy <deploy-target> --verbose`

This info should help us diagnose your issue more easily.

**Comment by afgallo** [comment]
Hi @achambers, have a look at the gist below:

https://gist.github.com/afgallo/d24cd8fbdd21aa92b7f03e60030a955b

**Comment by duizendnegen** [comment]
Hi @afgallo - I take full blame. I forgot to add 'return env;' add the default generated `deploy.js`. If you add this on line 25, that should fix it.

**Comment by afgallo** [comment]
Thanks for the fix @duizendnegen ! Worked like a charm!

I'm gonna have fun now, awesome work guys ;)

**Comment by ghedamat** [comment]
@duizendnegen mind opening a PR to fix the default?
we can keep this issue open in the meantime I think

**Comment by achambers** [comment]
@duizendnegen It is there -> https://github.com/ember-cli-deploy/ember-cli-deploy/blob/master/blueprints/ember-cli-deploy/files/config/deploy.js#L27

**Comment by duizendnegen** [comment]
@achambers it's not there on `ember-cli-deploy-azure`, I'll close this issue & publish a fix on the other side.
