### ISSUE TITLE
Bump broccoli?

### ISSUE THREAD

**Issue by sarupbanskota** [ember-cli-deploy/ember-cli-deploy#437]
Based on https://github.com/ember-cli-deploy/ember-cli-deploy/blob/master/package.json#L48, the `ember-cli-deploy` on master is using `"broccoli": "^0.13.2"`.

This version of broccoli uses `"handlebars": "^2.0.0",` https://github.com/broccolijs/broccoli/blob/v0.13.2/package.json#L28.

I wanted to check if there's any reason we cannot use the latest stable version of broccoli `v0.16.9`, https://github.com/broccolijs/broccoli/blob/v0.16.9/package.json#L28 since it uses `"handlebars": "^4.0.4"`.

Context: I ran one of my projects that uses `ember-cli-deploy` from `master` through [RetireJS](retirejs.github.io), and got complained about the vulnerability described at https://nodesecurity.io/advisories/61. 

If the version upgrade is acceptable, I can send in a PR to this repository.

Thanks!

**Comment by sarupbanskota** [comment]
This change also removes the dependency on `tiny-lr` https://github.com/broccolijs/broccoli/blob/v0.13.2/package.json#L32. 

`tiny-lr` relies on `debug` which in turn relies on `ms`. In this specific case, `ms 0.6.2`

ms 0.6.2 has known vulnerabilities: https://nodesecurity.io/advisories/46

**Comment by duizendnegen** [comment]
Yep, a PR would be perfect - I wonder whether we actually use broccoli anywhere in our pipeline (same w/ `broccoli-gzip`, is it not just `ember-cli-deploy-gzip` that uses it?) & can not outright remove the dependency.

**Comment by sarupbanskota** [comment]
I can't say I understand why @duizendnegen, but I see a reference here: https://github.com/ember-cli-deploy/ember-cli-deploy/blob/c3e94ddd48a89d30f456651cd366ffd0f980b625/ember-cli-build.js#L2

**Comment by sarupbanskota** [comment]
This can be closed now? If you can confirm broccoli isn't a dependency, I can send another PR removing it altogether.

**Comment by duizendnegen** [comment]
Thanks, I'll look at the broccoli part later (I think it's no dependency, but I'm waiting for others to confirm + do a sample deploy before removing it completely)

**Comment by sarupbanskota** [comment]
Thanks @duizendnegen! 

Any advice on when this fix might land on an npm package approximately, so I can roll it into my project?

**Comment by sarupbanskota** [comment]
Also, just realised that this will also help with https://nodesecurity.io/advisories/48, which I incorrectly reported at https://github.com/mishoo/UglifyJS2/issues/1394.

That's 3 vulnerabilities on one PR! Yay.

**Comment by duizendnegen** [comment]
I'll try and review most dependencies by Monday or Tuesday next week, and then I'll push for an update - my aim is to have this come out short term.

**Comment by sarupbanskota** [comment]
Thanks @duizendnegen! Keep me posted if possible :)

**Comment by duizendnegen** [comment]
FYI we released a new version now (https://github.com/ember-cli-deploy/ember-cli-deploy/releases/tag/v1.0.0-beta.2), also published to npm, which includes the fixes. Would be awesome if you could test this, as we need as much feedback as possible on the beta branch.
