### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by briancbarrow** [ember-cli-deploy/ember-cli-deploy#448]
I tried to install this and it is taking 30+ minutes to install. I am still waiting on it.  It gets stuck here:

![image](https://cloud.githubusercontent.com/assets/13695093/21964543/f724800e-db0a-11e6-9414-002c3ca6ba93.png)

Should I just wait it out?

**Comment by briancbarrow** [comment]
@lukemelia I left to do some family stuff for the day and just came back. 9 hours and zero progress was made. I am on a Windows but followed the guidelines for use on a windows machine. Not sure what else to do.

**Comment by ghedamat** [comment]
@briancbarrow I would suggest to kill the install and probably nombom  (npm cache clean, delete node_modules, npm install)

This way you will attempt a full install from scratch 

If it's still broken we could try to chat tomorrow on the #ec-deploy channel of the embercommunity slack

**Comment by briancbarrow** [comment]
Okay. I have another project I need to work on in the mean time so I will let you know what I get after doing that.

**Comment by BryanCrotaz** [comment]
I'm seeing the same problem

**Comment by jasonmit** [comment]
I'm also seeing this, I'll add more details if I can uncover what is happening.

**Comment by jasonmit** [comment]
Looks to be resolved in ember-cli 2.11.0 by https://github.com/ember-cli/ember-cli/pull/6525

**Comment by ghedamat** [comment]
@jasonmit that's great news!

please let us know if we can close the issue

**Comment by jasonmit** [comment]
@ghedamat I think this can we closed now
