### ISSUE TITLE
allowing plugins to disable other plugins?

### ISSUE THREAD

**Issue by raycohen** [ember-cli-deploy/ember-cli-deploy#454]
I'm working on [ember-cli-deploy-create-react-app](https://github.com/raycohen/ember-cli-deploy-create-react-app) as an alternative to the `ember-cli-deploy-build` plugin, which could allow users of [create-react-app](https://github.com/facebookincubator/create-react-app) to benefit from `ember-cli-deploy`.

For the most part, [it is working](http://ember-cli-deploy-sample.herokuapp.com/react).

As a user of create-react-app won't have an ember app to build, the `ember-cli-deploy-build` addon can't be used with `ember-cli-deploy-create-react-app`. Since [many plugin packs explicitly](https://github.com/ember-cli-deploy/ember-cli-deploy-lightning-pack/blob/master/package.json#L21) specify `ember-cli-deploy-build`, this means that currently a user must add [config to disable the ember build](https://github.com/raycohen/deployable-react-app/blob/master/config/deploy.js#L15-L22) in order to use a plugin pack. Without the extra config the build will error when it doesn't find an `ember-cli-build.js` file.

I attempted to use my plugin's `configure` hook to merge `pipeline.disabled.build: true` into the config, but it looks like the [disabled filter](https://github.com/ember-cli-deploy/ember-cli-deploy/blob/49c8a2f5046e750f5decfe90572c016ba8d7781f/lib/models/plugin-registry.js#L32) has already run by the time any hooks are called.

I can detect in my plugin's configure hook to see if the `config.pipeline.disabled.build` value is set, and output a warning to add it if missing. However it would be really nice to have some way for the plugin to do that for the user.

**Comment by achambers** [comment]
Hi @raycohen . Nice work on this dude. Loving it :)

So, one thing that comes to mind immediately is that plugins having the ability to disable other plugins seems a little bit intrusive. So, I could install a plugin and all of a sudden something else in my pipeline breaks because a different plugin that I relied upon has been disabled without me knowing.

Do you have any thoughts around this? Or what an API for what you require might look like?

Just thinking out loud here and I need to put some more time in to thinking through this use case but totally see where you're coming from.

Will let it stew for a while and see what rises to the top.

Nice work, once again 👍

**Comment by lukemelia** [comment]
I agree this is not something we want to allow. Options I can think of:

1) Have plugin packs specific to react ecosystem
2) Have the react plugin's README include instructions to users about disabling the build plugin
3) Have the build plugin have a configuration option that allows suppression, with a check for a context key by default. (This would be the most seamless for your goal but is the least _clean_, IMO.)

**Comment by raycohen** [comment]
I can see how allowing any plugin to arbitrarily turn others off could lead to problems.  Since this is specific to the build step, perhaps there can be a way for a plugin to specifically say "I'm the build step, turn off the ember build step if it is registered"

**Comment by lukemelia** [comment]
@raycohen This is what I was thinking in the third option. It's still odd in as much as there's no such thing as a "build step" per se, there is just zero or more plugins which happen to implement the `build` hook.

**Comment by duizendnegen** [comment]
I would stay step 1 is the most viable step - having `ember-cli-deploy-build` with an option of "please don't build" seems counterintuitive.

Longer term I would say that going in the direction of making `ember-cli-deploy` independent of `ember-cli`, i.e. `deployjs` and from there build for whatever specific environment you want is the right direction.

**Comment by achambers** [comment]
Yup, I'm for option one. We don't want to assume that only one plugin implements the build hook. 

Sounds to me like you just want your own plugin pack that happens to use the same plugins as the Lightning pack except for the build plugin. 

In fact you could make your existing ember-cli-deploy-create-react-app plugin that very plugin pack as well. So it pulls in all the ember-cli-deploy plugin deps and provides its own build hook implementation.

**Comment by achambers** [comment]
(a plugin can also be a plugin pack)

**Comment by raycohen** [comment]
I think a combination of options 1 and 2 will suffice. Agreed the alternatives are too awkward. I'll close this, thanks for taking a look!
