### ISSUE TITLE
Custom hash fingerprinting causing deploy issue

### ISSUE THREAD

**Issue by stevetyler** [ember-cli-deploy/ember-cli-deploy#462]
I'm using ember-cordova to create an iOS app and was having problems with fingerprinting where the signatures weren't matching between my cordova build and my ember deploy build. I've now changed my ember-cli-build options to use a customHash instead and that works now. However subsequent ember deploy builds are not updating my S3 assets even though I get an 'activated revision' success message. I presume this is to do with the revision data plugin? Do I need to disable it? Thanks for any advice

**Comment by lukemelia** [comment]
@stevetyler you may be using the manifest plugin, which skips uploading files when a file with the same name has been previously uploaded. If you are not fingerprinting your assets, then you should not use the manifest plugin.

**Comment by stevetyler** [comment]
Ok thanks Luke, I'm using the lightning pack so the manifest plugin doesn't show in my package.json . What's the best way to disable it? Should I uninstall the lightning pack and install the relevant plugins separately? Thanks again

**Comment by lukemelia** [comment]
@stevetyler sorry for the delay. You can install the relevant plugins separately, or follow he docs for Disabling Plugins below http://ember-cli-deploy.com/docs/v1.0.x/configuration/#advanced-plugin-configuration
