### ISSUE TITLE
[DOC] Document step-by-step creation of a plugin as an in-repo addon

### ISSUE THREAD

**Issue by lukemelia** [ember-cli-deploy/ember-cli-deploy#476]
@LevelbossMike @ghedamat and I discussed how in-repo-addon plugins have a low barrier to entry *IF* you know how to create and work with an in-repo-addon. Resolved to add docs to ember-cli-deploy.com showing exactly how to do this.

**Comment by amiel** [comment]
I hope #486 is what you're looking for.
