### ISSUE TITLE
revision ID not getting appended to the files

### ISSUE THREAD

**Issue by dprofsur** [ember-cli-deploy/ember-cli-deploy#489]
Hi,

In the dist file where the deploy files are getting build, the revision number is not getting updated at the end of the file

I am using the following `ember-cli-deploy` plugins
```
"ember-cli-deploy": "1.0.1",
 "ember-cli-deploy-lightning-pack": "1.1.2"
```

and my `deploy.js` file looks as below

```
var VALID_DEPLOY_TARGETS = [ //update these to match what you call your deployment targets
  'development'
];

module.exports = function(deployTarget) {
  var ENV = {
    build: {},
    redis: {
      allowOverwrite: true,
      keyPrefix: 'my-app:index'
    },
    s3: {
      prefix: 'my-app'
    }
  };

  if (deployTarget === 'development') {
    ENV.build.environment = 'development';
    ENV.s3 = {
     accessKeyId: process.env.ACCESS_KEY_ID,
     secretAccessKey: process.env.SECRET_ACCESS_KEY,
     bucket: process.env.BUCKET,
     region: process.env.REGION,
     filePattern: '**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf'
     +',woff,woff2,html}'
   }
  }
  return ENV;
}
```
what I understood from documentation is that the files generated for upload should be of format `<filename>-<revisionID>`. But when I run `ember deploy development` the following files are getting generated in the distFolder which gets uploaded to S3
```
my-app.css
my-app.js
brand.png
passed.png
test-support.js
tests.js
vendor.css
vendor.map
my-app.css.map
my-app.map
failed.png
test-support.css
test-support.map
tests.map
vendor.js
```
There is no revision ID and because of it when I try to upload the files the second time, the manifest doesn't picks the change and does not upload the changed file.

the `ember -v --verbose` is
```
ember-cli: 2.10.0
http_parser: 2.7.0
node: 6.10.1
v8: 5.1.281.95
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 58.2
modules: 48
openssl: 1.0.2k
os: darwin x64
```

**Comment by duizendnegen** [comment]
You are uploading development build to a development environment. To get what you expect, you need to upload a production build to a development environment.
` ENV.build.environment = 'development';` is what causes this behaviour.

Let me know if there's anything else unclear.

**Comment by dprofsur** [comment]
Thanks @duizendnegen that helped. All files are getting appended with `revision-id` apart from `index.html` file. It just goes as it is, and even before I trigger `ember deploy:activate development --revision=<revision_id>` the new code is already activated

**Comment by duizendnegen** [comment]
`index.html` shouldn't get a revision ID precisely. Maybe @lukemelia can say something about what's happening with Redis in this case?

**Comment by lukemelia** [comment]
The lightning pack is designed to deploy your index.html contents into redis. You have included html in the filePattern that is uploaded to S3, so it is being uploaded there. If you want to serve your HTML from S3, you should not be using the lightning pack and could instead consider https://github.com/Gaurav0/ember-cli-deploy-s3-pack.

**Comment by dprofsur** [comment]
Thanks @lukemelia for the help. After replacing `ember-cli-deploy-lighting-pack` with `ember-cli-deploy-s3-pack` I am able to activate different versions.
