### ISSUE TITLE
Feature Request: Activate Newest Deploy

### ISSUE THREAD

**Issue by joelkallman** [ember-cli-deploy/ember-cli-deploy#493]
I'd be happy to assist creating a pull request for this feature. I would just need some direction as to where to begin adding the new code.

**Currently my workflow is like so:**

`ember deploy production`
`ember deploy:list production`
`ember deploy:activate production --revision=XXXXX`

**What I would love to be able to do is as follows:**

`ember deploy production`
`ember deploy:activate production --newest`

If the `newest` flag is set, it would find the latest revision that would be listed from the `ember deploy:list production` command and activate that one.

**Comment by achambers** [comment]
Hi @joelkallman. I'm wondering whether you could actually do this via a custom plugin. Thinking out loud here but the `context` object that is passed in to each hook has a `context.commandOptions` property which is the options passed in to the command line.

Using this you could detect `--newest` in an early hook and then retrieve the most recent revision key and then set it on `context.commandOptions.revision` which would then meant that the -redis plugin will pick it up as if you'd passed it in. [LINK](https://github.com/ember-cli-deploy/ember-cli-deploy-redis/blob/master/index.js#L50)

This is assuming you're using the redis plugin.

The change you're requesting actually doesn't belong in this repo (ember-cli-deploy) and belongs in the -redis plugin repo, or whatever plugin you're using to upload and activate. And the logic would likely be close to what I described above, so implementing it in a separate plugin initially would be the preferred approach. If it seems to work and make sense, then maybe we can look at rolling it in to the core plugin at a later date.

Feel free to ask questions here if you like. Happy to assist where I can.

**Comment by mydea** [comment]
FYI, and if anyone else has the same issue, I made a small addon doing exactly that:

https://github.com/mydea/ember-cli-deploy-latest-revision

So you can do `ember deploy:activate production --revision=LATEST`.

**Comment by achambers** [comment]
I'm going to close this issue now as a) it isn't functionality that belongs in ecd core, and b) @mydea has spun up a plugin to do just this.

Great work @mydea
