### ISSUE TITLE
Split build and deploy

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli-deploy/ember-cli-deploy#494]
Deploying to the cloud works with current ember-cli-deploy `ember deploy prod`

However we also deploy into client cloud accounts, where we don't have write access to their cloud account. We want to be able to build and ship a zip to them where they can run deploy locally.

The zip should be uglified, so I want to run the full build process and deploy the already built files as a separate step.

Is this already possible or is this a feature request?

**Comment by lukemelia** [comment]
@BryanCrotaz Already possible. You would use a different `deployTarget` for each type of deployment you want to do, and configure the pipeline accordingly for that deploy target. Check the docs starting here: http://ember-cli-deploy.com/docs/v1.0.x/configuration/#additional-environments

We can reopen this if it doesn't solve your use case.

**Comment by BryanCrotaz** [comment]
We already use that to deploy to staging, canary, prod etc.

But for what is effectively an on-premise deploy, we need to send the client the built dist folder for them to deploy to their private cloud.

So I need the `build` and `deploy` steps to be separate. So `ember deploy` shouldn't do a build in this case, it should use a supplied `dist` folder or `dist.zip` which is already built and uglified (using the usual `ember build`).

**Comment by lukemelia** [comment]
The `build` step is just a plugin in your deploy pipeline. It can be excluded via configuration as shown in the docs link I posted.

**Comment by BryanCrotaz** [comment]
There isn't an example of disabling build - what is the build plugin called? I can't find a list of plugin names in the docs.

**Comment by BryanCrotaz** [comment]
Ah... ???
`ENV.pipeline.disabled.build = true;`

Then you put the prebuilt files in a `./dist` folder?

**Comment by duizendnegen** [comment]
You could even write your own build plugin which merely unzips the supplied
assets :)

**Comment by HarshRohila** [comment]
Skipping build and revision-data gives error
