### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token with gzip

### ISSUE THREAD

**Issue by ashrafhasson** [ember-cli-deploy/ember-cli-deploy#498]
When using `ember-cli-deploy-gzip` I get `Uncaught SyntaxError: Invalid or unexpected token` when loading the app in the browser. When disabling gzip in the pipeline, things work without any issues.

Here's what I'm using:
```
    "ember-cli-deploy": "^1.0.2",
    "ember-cli-deploy-build": "^1.1.1",
    "ember-cli-deploy-display-revisions": "^1.0.0",
    "ember-cli-deploy-gzip": "^1.0.1",
    "ember-cli-deploy-redis": "^1.0.2",
    "ember-cli-deploy-revision-data": "^1.0.0",
    "ember-cli-deploy-simply-ssh": "^1.0.0",
    "ember-cli-deploy-ssh-tunnel": "^1.0.0",
```

I'm uploading the app to my own server via `simply-ssh` but that shouldn't matter, I think.
Any hints as to what might the issue be here, please?

**Comment by duizendnegen** [comment]
Does your web server send out content encoding headers and does `simply-ssh` set those properties on the file?
Compare `simply-ssh` with e.g. `s3`, which, afaik, looks explicitly to see whether gzip encoding has had taken place.

**Comment by ashrafhasson** [comment]
It doesn't seem the server is setting the `Content Encoding: gzip` header, I assumed it would automatically for compressed files. Not sure if simply-ssh is setting any properties on the files (it calls [`node-ssh's putFiles`](https://github.com/AutoCloud/ember-cli-deploy-simply-ssh/blob/master/index.js#L53) on the file without any extra properties whether it's gzipped or not).

**Comment by duizendnegen** [comment]
View e.g. https://github.com/ember-cli-deploy/ember-cli-deploy-s3/blob/master/lib/s3.js#L151 - where s3 investigates `gzippedFiles` to see whether to set encoding on it explicitly or not.
Suggest to open a ticket with `simply-ssh` - let me know!
