### ISSUE TITLE
[DOC] 

### ISSUE THREAD

**Issue by hakilebara** [ember-cli-deploy/ember-cli-deploy#511]
Can `filePattern` have multiple patterns?
I have a json file at the root of my app folder that does not have a file extension: `foo-static-asset`. 
I can't modify the file name as 3rd party services depend on it on this URL `myapp.com/foo-static-asset`. 

```js
{
  filePattern: '**/*.{js,css,html,png,gif,ico,jpg,xml,txt,svg,json},foo-static-asset'
}
```

Is this pattern valid? Can multiple patterns be separated by a comma?

**Comment by LevelbossMike** [comment]
If the option does not support multiple file-patterns you can include a deploy-plugin multiple times with different options in the deploy pipeline: http://ember-cli-deploy.com/docs/v1.0.x/including-a-plugin-twice/

Does that solve your issue?

**Comment by dcyriller** [comment]
As you suggested, we ended up leveraging the pipeline option:
```js
ENV.pipeline = {
    alias: {
        s3: { as: ['s3-main', 's3-ios'] }
    }
}

ENV['s3-main'] = {
    ...,
    filePattern: '**/*.{js,css,html,png,gif,ico,jpg,xml,txt,svg,json}'
}

ENV['s3-ios'] = {
    ...,
    filePattern: 'apple-app-site-association'
}
```
It works well, thank you :)

**Comment by LevelbossMike** [comment]
Glad it works for your use-case :+1:. Closing for now.
