### ISSUE TITLE
"ember deploy production" broken by new broccoli-clean-css version in latest Ember releases

### ISSUE THREAD

**Issue by danr1979** [ember-cli-deploy/ember-cli-deploy#512]
Hi.

I have just updated one of our Ember applications to ember-cli version 3.7.1 and when running `ember deploy production` I received the following error during the clean up stage:

```
Deploying [>-----] 17% [plugin: build -> build]Circular dependency: ../../../../tmp/broccoli-25576aYIwHAdOZric/cache-278-rollup/build/-private/system/model/model.js -> ../../../../tmp/broccoli-25576aYIwHAdOZric/cache-278-rollup/build/-private/system/model/internal-model.js -> ../../../../tmp/broccoli-25576aYIwHAdOZric/cache-278-rollup/build/-private/system/references.js -> ../../../../tmp/broccoli-25576aYIwHAdOZric/cache-278-rollup/build/-private/system/references/belongs-to.js -> ../../../../tmp/broccoli-25576aYIwHAdOZric/cache-278-rollup/build/-private/system/model/model.js
cleaning up...
- build failed
BuildError: assets/vendor.css: An error found while optimizing CSS with clean-css:
  * Ignoring remote @import of "https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin" as resource is not allowed and after other content.

clean-css dangerously ignores this error but broccoli-clean-css doesn't, because it's much more reasonable to update the CSS to fix all problems than to pretend that you didn't see the errors.
        in /tmp/broccoli-25576aYIwHAdOZric/out-460-simple_concat_concat_concat_vendor_styles_assets_vendor_css
        at broccoli-persistent-filter:CleanCSSFilter
```

We also have another ember application that was upgraded to 3.7.1 a while ago and that is deploying fine.  I found this odd but when I looked in the node_modules folder at the "broccoli-clean-css" package on the application that was deploying ok I found it used version 1.1.0 whereas the application that would not deploy was using version 2.0.1.  So it seemed like version 2.0.1 did not like the remote imports of Google Fonts whereas version 1.1.0 was fine with it.

I ran `npm ls broccoli-clean-css` on the application that was deploying and got the following:

```
ember-cli@3.7.1
  └─┬ ember-cli-preprocess-registry@3.1.2
    └── broccoli-clean-css@1.1.0 
```

and then ran the same command on the application that was failing to deploy and got:

```
ember-cli@3.7.1
  └─┬ ember-cli-preprocess-registry@3.2.1
    └── broccoli-clean-css@2.0.1 
```

So, "ember-cli-preprocess-registry" is the package that is dependent on broccoli-clean-css.  It also seems like ember-cli-preprocess-registry has been updated from 3.1.2 to 3.2.1 since ember-cli 3.7.1 was first released and this is what was causing the difference in deployment behaviour between our applications.

I have fixed the issue by running `npm install ember-cli-preprocess-registry@3.1.2` to downgrade the package and thus the version of broccoli-clean-css but I thought you might want to look at the issue that broccoli-clean-css has with CSS remote import statements.  I suspect that others will start getting problems with deployments too as they update their Ember applications.

It is worth noting that both of our Ember applications built fine when running `ember serve` so the issue is _only_ when using ember-cli-deploy and running `ember deploy production`.

**Comment by LevelbossMike** [comment]
Thanks for reporting this. I'll setup a test project in a second to verify ember-cli-deploy still works with 3.7.1

**Comment by LevelbossMike** [comment]
@danr1979 I created a brand new app with `ember-cli@3.7.1`, setup a deployment with `ember-cli-deploy-s3-index` and it deployed and updated fine.

Can you push a repository that reproduces this problem so we can debug the issue you are seeing?

As always we are happy to help ❤️

**Comment by danr1979** [comment]
Hi @LevelbossMike.

Thanks for responding to this so quickly.  I think the issue lies with the fact that we are using the ember-semantic-ui add-on (https://github.com/Semantic-Org/Semantic-UI-Ember).  This contains css files that use the statement:

```
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
```

which is what broccoli-clean-css seems to be objecting to.  I'm not sure why the @import statement is a bad thing and, as I say, it didn't cause any issues in broccoli-clean-css version 1.1.0?  

I guess this isn't really an ember-cli-deploy issue but my concern was that there might be other addons that use similar imports that cause the deployment to fail so I thought I'd report it so others might see this and understand a bit more about what is causing the issue.  Maybe someone might know why the @import is causing an error?

**Comment by LevelbossMike** [comment]
@danr1979 it really looks like this is something you should raise on that particular addon then. I'm not sure what these two other addons are doing to the build so their collaborators might now better what might be causing this.

`ember-cli-deploy` seems to work as expected.
