### ISSUE TITLE
Trying to update the azure lighning pack

### ISSUE THREAD

**Issue by wayne-o** [ember-cli-deploy/ember-cli-deploy#513]
Hi

I am trying to update the azure lighning pack and i keep getting this output:
```
WARNING: No plugins installed/enabled


ember-cli-deploy works by registering plugins in it's pipeline.


In order to execute a deployment you must install at least one ember-cli-deploy compatible plugin.


Visit http://ember-cli-deploy.com/plugins/ for a list of supported plugins.


fetchRevisions not implemented by any registered plugin
```

I have NPM linked the packages into my ember app (actually i have linked the 2 plugins into the lighning pack and then that into the ember app)

The code so far can be seen here: 

https://github.com/wayne-o/ember-cli-deploy-azure
https://github.com/wayne-o/ember-cli-deploy-azure-blob
https://github.com/wayne-o/ember-cli-deploy-azure-tables

I have made sure the correct keywords are there and also the plugins are named correctly so I am confused as to why I am getting this output.

I am new to creating addons so I expect its a problem my end :)

**Comment by duizendnegen** [comment]
Hi! Do you also have `ember-cli-deploy-azure` in your `package.json`? `ember-cli-deploy` gobbles up to be included plugins in a specific way, so just trying to check whether you're going the right thing.
The easiest approach to all of this would be forking the `ember-cli-deploy-azure-blob` and `-tables` plugins, and opening PRs with your fixes pointing to the original repos, instead of creating new plugins.

**Comment by wayne-o** [comment]
Problem with that is that the existing ones are so far behind - it's just easier to create from scratch - or I thought it would be!

**Comment by wayne-o** [comment]
Ah you're the creator of the existing ones :) my plan was to get these working then copy the code into a branch and submit a pr - i assumed the ember addon base had changed a lot so i went this path

**Comment by wayne-o** [comment]
maybe I shoudl rewind a bit and start over

**Comment by duizendnegen** [comment]
So that's the tricky part - actually, Ember CLI Deploy plugins are not Ember addons - they're Node plugins, instead - they don't operate during the normal Ember lifecycle, but before that - the route of "creating an Ember addon from scratch" is not the right route anyway, unfortunately.

**Comment by wayne-o** [comment]
ok I am going to start over and see where I can get to

**Comment by wayne-o** [comment]
I have a feeling this projetc has fallen behind - is it still actively maintained? If I do a simple test like 
```ember deploy:list production```
I get this output 
```-   timestamp           | revision```
now, if I for instance go into your ember-cli-deploy-azure-tables code and  change fetchRevisions to this:
```
fetchRevisions: function(context) {
        return this._list(context).then(function(revisions) {
          console.log(JSON.stringify(revisions))
          return {
            revisions: revisions
          };
        });
      },
```
I get a whole lot of revisions blurted out in the correct format according to this (https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions)
```{"revision":"project-name:10db6fba","timestamp":1534424161806,"active":false}```
So that method is being called - it's just being mangled further up the pipeline...

**Comment by wayne-o** [comment]
I think my problem is that i can update the azure related projects but something tells me the job is bigger than just that

**Comment by wayne-o** [comment]
it looks like here it's looking for `revisionData`
https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/blob/master/index.js#L35
but we are returning data in this format:
```[
  {
    revision: 'abc123', // mandatory
    version: 'v1',
    timestamp: 1438232435000, // milliseconds since epoch
    deployer: 'cats'
  },
  {
    revision: 'def456',
    version: 'v2',
    timestamp: 1032123128000,
    deployer: 'dogs',
    active: true // indicate whether this revision is activated
  }
]```

**Comment by wayne-o** [comment]
this no longer works I think

https://github.com/ember-cli-deploy/ember-cli-deploy-display-revisions/blob/master/lib/legacy-table.js#L13

**Comment by duizendnegen** [comment]
Hm, it could definitely be that `ember-cli-deploy-azure` became stale and is not up to date with what is there on `ember-cli-deploy-display-revisions`.

**Comment by wayne-o** [comment]
I think display revisions no longer works

**Comment by wayne-o** [comment]
in fact changing that line to console.log makes it output what you'd expect... so something is up with the ui that's being passed in

**Comment by wayne-o** [comment]
This also doesn't work - https://github.com/duizendnegen/ember-cli-deploy-azure-tables/blob/a40b23e9cc08192096be3abf5345299e4f6c20ef/index.js#L44

Because revisionData is alsways null - should it be initialRevisionData?

**Comment by wayne-o** [comment]
Where does that ui object come from? ember cli?

**Comment by wayne-o** [comment]
OK so I have done some more digging and it looks like this oes actually work - it just looks like it doesn't because the logging is broken!!
